# Generated by Django 5.0.4 on 2024-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0002_alter_product_in_stock_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
