# Generated by Django 5.0.4 on 2024-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authority',
            field=models.CharField(max_length=36),
            preserve_default=False,
        ),
    ]
