# Generated by Django 5.0.4 on 2024-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product_quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
